### ISSUE TITLE
Dont mutate query/batch when executing queries

### ISSUE THREAD

**Issue by Zariel** [apache/cassandra-gocql-driver#1229]
We shouldnt mutate query or batch when executing, looks like we store the new PageState on the query which should only be on the iter.

**Comment by dankinder** [comment]
We were just bit by this. We had a query object we were reusing, where the first use didn't read all the records and closed the iterator early, and then the second query was skipping over the records that were already read, even though it was a brand new iterator.

Until it is made safe I suggest updating the documentation to note that reuse of a query object is not safe.

**Comment by dahankzter** [comment]
To be fair @dankinder the documentation for `Session` states that it is safe for concurrent use but the `Query` object has no such doc and assuming safety is never safe.
If they are not accessed concurrently then maybe it can be that the pageState is not reset properly. Maybe it should be reset in the `defaultsFromSession` I am not sure.

**Comment by dankinder** [comment]
Yeah in my case it is not an issue with concurrent access. It does sound like the page state is simply not reset. Maybe fixing that would be quicker/easier than moving where the page state is stored?

**Comment by martin-sucha** [comment]
Related to #1508, #1511 and #1447

**Comment by joao-r-reis** [comment]
closing this in favor of #1447
