### ISSUE TITLE
Donate GoCQL to Apache Cassandra [YOUR ACTION REQUIRED]

### ISSUE THREAD

**Issue by michaelsembwever** [apache/cassandra-gocql-driver#1751]
To all the authors,

We are working on donating this project to the Apache Software Foundation (ASF) to be formally part of the Apache Cassandra project.

To do that we need you to perform two actions:
1.  Sign Apache's CLA 
2.  Agree to have your past contributions donated to the Apache Software Foundation (using the signed CLA)

   

 1) The CLA and its instructions is found [here](https://www.apache.org/licenses/contributor-agreements.html#clas). 
We need the (Individual) ICLA signed from you, and emailed to [secretary@apache.org](mailto:secretary@apache.org)  You do not need to choose/fill out an Apache ID.   Once you have done this, or if you already have an ICLA submitted to the ASF, please let us know.

 2) An agreement from you to have your contributions from this project donated.  A simple `+1` comment on this issue is all that is required.  This agreement must be in addition to us (the ASF) receiving a signed ICLA from you.

  
  

--- More info ---

The gocql driver is a quality body of open source work, and an important library for many Cassandra users.  Martin (and Chris, the two maintainers) recently brought to our attention the driver's stagnate state, asking for new maintainers and contributors to step forward.  https://groups.google.com/g/gocql/c/v0FruczBb2w 

The Cassandra project has wanted to bring it into the project formally for a number of years now, and has finally figured out the approach to make this happen with regards to the code's (your) IP.  With the legal path clear, and a blessing from @martin-sucha  and @Zariel, and a number of you already, the move of the driver into the project has formally begun.  https://lists.apache.org/thread/nwsfw4btx69rj8y1ly0pcp5o44yct7ng  

--- Authors ---

Christoph Hack @tux21b 
Jonathan Rudenberg @titanous 
Thorsten von Eicken @tve 
Matt Robenolt @mattrobenolt  
Phillip Couto @phillipCouto
Niklas Korz  @niklaskorz 
Nimi Wariboko Jr  ?? 
Ghais Issa @ghais 
Sasha Klizhentas ??
Konstantin Cherkasov  @coxx @kofatol
Ben Hood @0x6e6562 
Pete Hopkins @petehatduck @petehopkins 
Chris Bannister @Zariel 
Maxim Bublis @satori 
Alex Zorin @alexzorin 
Kasper Middelboe Petersen @fantyz 
Harpreet Sawhney @harpreet-sawhney 
Charlie Andrews @cwndrws 
Stanislavs Koikovs @skoikovs 
Dan Forest @dbxfb 
Miguel Serrano @miguelvps 
Stefan Radomski @sradomski
Josh Wright @JshWright 
Jacob Rhoden @Jacobr23
Ben Frye @benfrye 
Fred McCann @fmccann
Dan Simmons @dsimmons 
Muir Manders @muirdm 
Sankar P @psankar 
Julien Da Silva @juliendsv 
Dan Kennedy @dankennedy 
Nick Dhupia ??
Yasuharu Goto @matope 
Jeremy Schlatter @jeremyschlatter 
Matthias Kadenbach ??
Dean Elbaz @deane 
Mike Berman @mikebthun 
Dmitriy Fedorenko @c0va23 
Zach Marcantel @zmarcantel 
James Maloney @ james-maloney @Jpmaloiv @Jimmy3850
Ashwin Purohit @purohit 
Dan Kinder @dankinder 
Oliver Beattie @obeattie 
Justin Corpron @jncorpron @justinretailnext 
Miles Delahunty @mdelah 
Zach Badgett @zachbadgett 
Maciek Sakrejda @msakrejda 
Jeff Mitchell @jefferai 
Baptiste Fontaine @bfontaine 
Matt Heath @mattheath 
Jamie Cuthill @jamiecuthill 
Adrian Casajus @acasajus 
John Weldon @johnweldon 
Adrien Bustany @abustany 
Andrey Smirnov @smira 
Adam Weiner @adamweiner 
Daniel Cannon @dancannon 
Johnny Bergström @balboah 
Adriano Orioli @TheOrioli 
Claudiu Raveica @craveica 
Artem Chernyshev @Unix4ever 
Ference Fu @fym201 
LOVOO @lovoo
nikandfor @nikandfor 
Anthony Woods @woodsaj 
Alexander Inozemtsev ??
Rob McColl @robmccoll 
Viktor Tönköl @tonkolviktor 
Ian Lozinski ??
Michael Highstead @Highstead 
Sarah Brown @esbie 
Caleb Doxsey @calebdoxsey 
Frederic Hemery @Arkelenia @fhemery
Pekka Enberg @penberg 
Mark M @mark-i-m 
Bartosz Burclaf ??
Marcus King @marcusking01 @king-mork @marcus-king @marcusKng01 
Andrew de Andrade @andrewdeandrade 
Robert Nix @robert-nix @rpural @robertcnix @rnix @robertnix
Nathan Youngman @nathany 
Charles Law @clawconduce 
Nathan Davies @nathj07 
Bo Blanton @uacfboblanton @bobbdelsol
Vincent Rischmann @vrischmann 
Jesse Claven @jesse-c 
Derrick Wippler @thrawn01 
Leigh McCulloch @leighmcculloch 
Ron Kuris @rkuris 
Raphael Gavache @raphaelgavache 
Yasser Abdolmaleki ??
Krishnanand Thommandra @kthommandra 
Blake Atkinson @robusto 
Dharmendra Parsaila ??
Nayef Ghattas @Gandem 
Michał Matczuk @mmatczuk 
Ben Krebsbach @bkrebsbach 
Vivian Mathews @inf-rno 
Sascha Steinbiss @satta 
Seth Rosenblum @sethrosenblum 
Javier Zunzunegui @JavierZunzunegui 
Luke Hines ??
Zhixin Wen @zhixinwen 
Chang Liu @changliuau 
Ingo Oeser @nightlyone 
Jacob Greenleaf @jacobgreenleaf 
Alex Lourie @alourie 
Marco Cadetg @domcyrus 
Karl Matthias @relistan 
Thomas Meson @zllak 
Martin Sucha @martin-sucha 
Pavel Buchinchik @Bychin 
Rintaro Okamura @rinx 
Yura Sokolov @funny-falcon-at-joomcode 
Jorge Bay @jorgebay 
Dmitriy Kozlov @DmitriyKozl @BigKozlowski @MrDimk @KozlovDmitry @MblWa @Kozlovxdm @KozlovDser @Dmtrkozl @dmitriykozlov @invader150
Alexey Romanovsky @alexus1024
Jaume Marhuenda Beltran @beltran 
Piotr Dulikowski @piodul 
Árni Dagur @ArniDagur 
Tushar Das @tushardas 
Maxim Vladimirskiy @horkhe 
Bogdan-Ciprian Rusu @bcrusu 
Yuto Doi @yutod 
Krishna Vadali @saikrishnavadali05 @kkvadali @vadalikrishna @wq4885 @SaiKrishna0778 
Jens-W. Schicke-Uffmann @Drahflow 
Ondrej Polakovič @ medasx
Sergei Karetnikov @sergeikaretnikov 
Stefan Miklosovic @smiklosovic 
Adam Burk ??
Valerii Ponomarov @vponomaryov 
Neal Turett @turettn 
Doug Schaapveld @djschaap 
Steven Seidman @sseidman 
Wojciech Przytuła @wprzytula 
João Reis @joao-r-reis 
Lauro Ramos Venancio @laurovenancio 
Dmitry Kropachev @ dkropachev
Oliver Boyle @olib963 
Jackson Fleming @jfleming-ic 
Sylwia Szunejko @sylwiaszunejko 

(All apologies if you have been accidentally mentioned, not all authors were easy to uniquely identify.)

**Comment by michaelsembwever** [comment]
Matt Heath @mattheath
Jamie Cuthill @jamiecuthill
Adrian Casajus @acasajus
John Weldon @johnweldon
Adrien Bustany @abustany
Andrey Smirnov @smira
Adam Weiner @adamweiner
Daniel Cannon @dancannon
Johnny Bergström @balboah
Adriano Orioli @TheOrioli
Claudiu Raveica @craveica
Artem Chernyshev @Unix4ever
Ference Fu @fym201
LOVOO @lovoo
nikandfor @nikandfor
Anthony Woods @woodsaj
Alexander Inozemtsev ??
Rob McColl @robmccoll
Viktor Tönköl @tonkolviktor
Ian Lozinski ??
Michael Highstead @Highstead
Sarah Brown @esbie
Caleb Doxsey @calebdoxsey
Frederic Hemery @Arkelenia @fhemery
Pekka Enberg @penberg

**Comment by michaelsembwever** [comment]
Dmitriy Kozlov @DmitriyKozl @BigKozlowski @MrDimk @KozlovDmitry @MblWa @Kozlovxdm @KozlovDser @Dmtrkozl @dmitriykozlov @invader150
Alexey Romanovsky @alexus1024
Jaume Marhuenda Beltran @beltran
Piotr Dulikowski @piodul
Árni Dagur @ArniDagur
Tushar Das @tushardas
Maxim Vladimirskiy @horkhe
Bogdan-Ciprian Rusu @bcrusu
Yuto Doi @yutod
Krishna Vadali @saikrishnavadali05 @kkvadali @vadalikrishna @wq4885 @SaiKrishna0778
Jens-W. Schicke-Uffmann @Drahflow
Ondrej Polakovič @ medasx
Sergei Karetnikov @sergeikaretnikov
Stefan Miklosovic @smiklosovic
Adam Burk ??
Valerii Ponomarov @vponomaryov
Neal Turett @turettn
Doug Schaapveld @djschaap
Steven Seidman @sseidman
Wojciech Przytuła @wprzytula
João Reis @joao-r-reis
Lauro Ramos Venancio @laurovenancio
Dmitry Kropachev @ dkropachev
Oliver Boyle @olib963
Jackson Fleming @jfleming-ic
Sylwia Szunejko @sylwiaszunejko

**Comment by smira** [comment]
+1

**Comment by smiklosovic** [comment]
+1

**Comment by rinx** [comment]
+1

**Comment by dankinder** [comment]
+1

**Comment by jorgebay** [comment]
+1

**Comment by penberg** [comment]
+1

**Comment by fmccann** [comment]
+1

**Comment by fmccann** [comment]
I've submitted Apache's CLA.

Thanks,


— Fred McCann
(862) 204-9006
***@***.***

**Comment by miguelvps** [comment]
+1

**Comment by zhixinwen** [comment]
+1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abustany** [comment]
+1

**Comment by joao-r-reis** [comment]
+1

**Comment by niklaskorz** [comment]
My contributions were minimal and none of the lines I contributed are included in today's HEAD of gocql. Thus you don't need my permission to relicense future versions of gocql. Feel free to remove me from AUTHORS.

https://github.com/gocql/gocql/commits/master/?author=niklaskorz

**Comment by c0va23** [comment]
+1

**Comment by johnweldon** [comment]
I'm not interested in signing the ICLA; I'm happy to contribute the code I have, but it's not worth it to me to go through the hassle of signing a PDF manually and emailing it, and I'm not interested in publishing the details asked for in the PDF.

**Comment by tve** [comment]
+1

**Comment by robmccoll** [comment]
+1 - CLA sent

**Comment by djschaap** [comment]
+1

**Comment by Zariel** [comment]
+1

**Comment by purohit** [comment]
+1Message ID: ***@***.***>

>

**Comment by titanous** [comment]
+1

**Comment by jeremyschlatter** [comment]
+1

**Comment by DmitriyKozl** [comment]
My contributions were minimal and none of the lines I contributed are included in today's HEAD of gocql. Thus you don't need my permission to relicense future versions of gocql. Feel free to remove me from AUTHORS.

**Comment by nightlyone** [comment]
+1

**Comment by fhemery** [comment]
I never contributed to this project, but you pinged my homonym who probably did already, so no action to be taken 😄

**Comment by medasx** [comment]
+1

**Comment by satta** [comment]
+1, ICLA sent

**Comment by mmatczuk** [comment]
+1

**Comment by jfleming-ic** [comment]
+1

**Comment by bfontaine** [comment]
+1, ICLA sent

**Comment by calebdoxsey** [comment]
+1, ICLA sent

**Comment by vponomaryov** [comment]
+1

**Comment by acasajus** [comment]
+1

**Comment by inf-rno** [comment]
+1

**Comment by zllak** [comment]
+1

**Comment by TheOrioli** [comment]
+1

**Comment by yutod** [comment]
My contributions were minimal and none of the lines I contributed are included in today's HEAD of gocql. Thus you don't need my permission to relicense future versions of gocql. Feel free to remove me from AUTHORS.

**Comment by matope** [comment]
+1, ICLA sent.

**Comment by alourie** [comment]
I won't bother signing the CLA, and this has been in the works since I was part of the project long ago in 2018.

So just +1.

**Comment by sethrosenblum** [comment]
+1

**Comment by phillipCouto** [comment]
+1

**Comment by adamweiner** [comment]
+1

**Comment by jncorpron** [comment]
+1

**Comment by michaelsembwever** [comment]
Thanks everyone for very fast responses, this has taken many of us by surprise and made us super happy.

I'm tracking this work in https://docs.google.com/spreadsheets/d/1sgdOdgfoY-Ttwj-EGE7KY_97VRfaBKlOP3E4PQfRhxc/edit#gid=0

Some of you mentioned that you won't sign the CLA as your work is trivial and/or no longer in today's HEAD.  This is entirely legit, and it's appreciated it's been picked up on.  The intent is to transfer the full git history, and so past work will be honoured via those git commits and the license and authors declaration at those moments in time.

Those of you that haven't yet responded, I will start trying to reach out to you on email and linkedin.
We are aiming to submit the donation mid-June.

**Comment by michaelsembwever** [comment]
@vrischmann, you submitted the CLA successfully, but there's no `+1` here from you to confirm your work in this project can be donated (using that CLA).

@purohit and @jeremyschlatter, your submitted CLA's haven't been accepted due to missing/incomplete info in the form.  You should have received an email from Craig Russell.

**Comment by vrischmann** [comment]
Sorry. +1 for me.

**Comment by Gandem** [comment]
+1

**Comment by psankar** [comment]
+1

But not sending any CLA as my changes would be trivial

**Comment by zackslash** [comment]
+1

**Comment by burkad01** [comment]
+1

**Comment by obeattie** [comment]
+1. ICLA also sent.

**Comment by clawconduce** [comment]
ICLA sent. FYI, this is an old account tied and the email address associated with the account/commits no longer exists

**Comment by sylwiaszunejko** [comment]
+1, ICLA sent

**Comment by horkhe** [comment]
+1. But my contribution was just a few lines of code. You have my full permission to do whatever you want with those changes. Going through the ICLA routine seems line an overkill for such a small contribution.

**Comment by jeremyschlatter** [comment]
> @jeremyschlatter, your submitted CLA's haven't been accepted due to missing/incomplete info in the form. You should have received an email from Craig Russell.

My contribution was a single trivial typo fix. You have my full permission to do anything you want with it. I would prefer not to complete the ICLA if it's not needed.

**Comment by woodsaj** [comment]
+1 and ICLA sent

**Comment by dankennedy** [comment]
+1 . My contribution was minor so please feel free to do as you want with it.

**Comment by domcyrus** [comment]
+1. Small contribution, feel free to do whatever.

**Comment by Unix4ever** [comment]
+1

**Comment by Arkelenia** [comment]
+1. Small contribution, feel free to do whatever

**Comment by cwndrws** [comment]
+1

**Comment by martin-sucha** [comment]
I'm happy to announce that Kiwi.com signed the Corporate CLA and the company agrees for all contributions that are owned by Kiwi.com in the gocql project's code repository and its forks available at https://github.com/gocql/gocql, https://github.com/kiwicom/gocql and https://github.com/scylladb/gocql to be donated to the Apache Software Foundation using the Corporate CLA.

I am also donating contributions in the gocql repositories mentioned above that I own personally using the Individual CLA.

**Comment by craveica** [comment]
+1. Small contributions, feel free to do whatever

**Comment by turettn** [comment]
+1

**Comment by michaelsembwever** [comment]
Thank you everyone for taking the time to update this issue, or email us back.

We are ready to move forward with the donation.

We currently have 71 authors that we haven't been able to reach, whom in total touch 78 commits.
If you know of any of these people and have contact details for them, please help us and ping them to this issue. 

If we do not hear from them we will either a) assume we have taken all reasonable actions (due diligence) to contact them and make the copyright re-assignment in good faith and in spirit with the majority that have agreed, or b) dual license and copyright work they have contributed (that still exists in master and v2.dev).

They are the following:
 
Christoph Hack @tux21b
Matt Robenolt @mattrobenolt
Niklas Korz  @niklaskorz
Nimi Wariboko Jr ??
Ghais Issa @ghais
Sasha Klizhentas ??
Konstantin Cherkasov @coxx @kofatol
Ben Hood @0x6e6562
Pete Hopkins @petehatduck @petehopkins
Maxim Bublis @satori
Alex Zorin @alexzorin
Kasper Middelboe Petersen @fantyz
Harpreet Sawhney @harpreet-sawhney
Stanislavs Koikovs @skoikovs
Dan Forest @dbxfb
Stefan Radomski @sradomski
Josh Wright @JshWright
Jacob Rhoden @Jacobr23
Ben Frye @benfrye
Muir Manders @muirdm
Julien Da Silva @juliendsv
Nick Dhupia ??
Matthias Kadenbach ??
Dean Elbaz @deane
Mike Berman @mikebthun
Zach Marcantel @zmarcantel
James Maloney @ james-maloney @Jpmaloiv @Jimmy3850
Miles Delahunty @mdelah
Zach Badgett @zachbadgett
Maciek Sakrejda @msakrejda
Jeff Mitchell @jefferai
Matt Heath @mattheath
Jamie Cuthill @jamiecuthill
Daniel Cannon @dancannon
Johnny Bergström @balboah
Ference Fu @fym201
LOVOO @lovoo
Viktor Tönköl @tonkolviktor
Ian Lozinski ??
Michael Highstead @Highstead
Mark M @mark-i-m
Bartosz Burclaf ??
Marcus King @marcusking01 @king-mork @marcus-king @marcusKng01
Andrew de Andrade @andrewdeandrade
Robert Nix @robert-nix @rpural @robertcnix @rnix @robertnix
Nathan Davies @nathj07
Bo Blanton @uacfboblanton @bobbdelsol
Derrick Wippler @thrawn01
Leigh McCulloch @leighmcculloch
Ron Kuris @rkuris
Raphael Gavache @raphaelgavache
Yasser Abdolmaleki ??
Krishnanand Thommandra @kthommandra
Blake Atkinson @robusto
Dharmendra Parsaila ??
Javier Zunzunegui @JavierZunzunegui
Chang Liu @changliuau
Jacob Greenleaf @jacobgreenleaf
Pavel Buchinchik @Bychin
Yura Sokolov @funny-falcon-at-joomcode
Alexey Romanovsky @alexus1024
Jaume Marhuenda Beltran @beltran
Piotr Dulikowski @piodul
Árni Dagur @ArniDagur
Tushar Das @tushardas
Bogdan-Ciprian Rusu @bcrusu
Krishna Vadali @saikrishnavadali05 @kkvadali @vadalikrishna @wq4885 @SaiKrishna0778
Jens-W. Schicke-Uffmann @Drahflow
Lauro Ramos Venancio @laurovenancio
Dmitry Kropachev @ dkropachev
Oliver Boyle @olib963

**Comment by michaelsembwever** [comment]
…continued…
Bo Blanton @uacfboblanton @bobbdelsol
Derrick Wippler @thrawn01
Leigh McCulloch @leighmcculloch
Ron Kuris @rkuris
Raphael Gavache @raphaelgavache
Yasser Abdolmaleki ??
Krishnanand Thommandra @kthommandra
Blake Atkinson @robusto
Dharmendra Parsaila ??
Javier Zunzunegui @JavierZunzunegui
Chang Liu @changliuau
Jacob Greenleaf @jacobgreenleaf
Pavel Buchinchik @Bychin
Yura Sokolov @funny-falcon-at-joomcode
Alexey Romanovsky @alexus1024
Jaume Marhuenda Beltran @beltran
Piotr Dulikowski @piodul
Árni Dagur @ArniDagur
Tushar Das @tushardas
Bogdan-Ciprian Rusu @bcrusu
Krishna Vadali @saikrishnavadali05 @kkvadali @vadalikrishna @wq4885 @SaiKrishna0778
Jens-W. Schicke-Uffmann @Drahflow
Lauro Ramos Venancio @laurovenancio
Dmitry Kropachev @ dkropachev
Oliver Boyle @olib963

**Comment by michaelsembwever** [comment]
> …dual license and copyright work they have contributed

Using the following gives a list of (the 109) files we need to dual-license…
```
comm -12 <(git ls-files) <(git log --all -G "christoph@tux21b.org|mattr@disqus.com|korz.niklask@gmail.com|nimi@channelmeter.com|klizhentas@gmail.com|k.cherkasoff@gmail.com|0x6e6562@gmail.com|phopkins@gmail.com|b@codemonkey.ru|git@zor.io|me@phant.dk|harpreet.sawhney@gmail.com|bonjour@dan.tf|gibheer@zero-knowledge.org|jshwright@gmail.com|jacob.rhoden@gmail.com|benfrye@gmail.com|muir@retailnext.net|julien.dasilva@gmail.com|nick.dhupia@gmail.com|matthias.kadenbach@gmail.com|elbaz.dean@gmail.com|evencode@gmail.com|zmarcantel@gmail.com|jamessagan@gmail.com|miles.delahunty@gmail.com|zach.badgett@gmail.com|jeffrey.mitchell@gmail.com|matt@mattheath.com|jamie.cuthill@gmail.com|daniel@danielcannon.co.uk|johnny@joonix.se|fym201@msn.com|opensource@lovoo.com|ian.lozinski@gmail.com|highstead@gmail.com|m.mim95@gmail.com|burclaf@gmail.com|marcusking01@gmail.com|andrew@deandrade.com.br|robert@nicerobot.org|bo.blanton@gmail.com|thrawn01@gmail.com|leigh@leighmcculloch.com|swcafe@gmail.com|yasser@yasser.ca|devtkrishna@gmail.com|me@blakeatkinson.com|d4dharmu@gmail.com|javier.zunzunegui.b@gmail.com|changliu.it@gmail.com|jacob@jacobgreenleaf.com|p.buchinchik@gmail.com|y.sokolov@joom.com|funny.falcon@gmail.com|alexus1024+gocql@gmail.com|jaumemarhuenda@gmail.com|piodul@scylladb.com|tushar.das5@gmail.com|bogdanciprian.rusu@crowdstrike.com|tejavadali@gmail.com|drahflow@gmx.de|lauro.venancio@incognia.com|dmitry.kropachev@gmail.com|pleasedontspamme4321+gocql@gmail.com|Christoph Hack|Matt Robenolt|Niklas Korz|Nimi Wariboko Jr|Sasha Klizhentas|Konstantin Cherkasov|Ben Hood|Pete Hopkins|Maxim Bublis|Alex Zorin|Kasper Middelboe Petersen|Harpreet Sawhney|Dan Forest|Stefan Radomski|Josh Wright|Jacob Rhoden|Ben Frye|Muir Manders|Julien Da Silva|Nick Dhupia|Matthias Kadenbach|Dean Elbaz|Mike Berman|Zach Marcantel|James Maloney|Miles Delahunty|Zach Badgett|Jeff Mitchell|Matt Heath|Jamie Cuthill|Daniel Cannon|Johnny Bergström|Ference Fu|LOVOO|Ian Lozinski|Michael Highstead|Mark M|Bartosz Burclaf|Marcus King|Andrew de Andrade|Robert Nix|Bo Blanton|Derrick Wippler|Leigh McCulloch|Ron Kuris|Yasser Abdolmaleki|Krishnanand Thommandra|Blake Atkinson|Dharmendra Parsaila|Javier Zunzunegui|Chang Liu|Jacob Greenleaf|Pavel Buchinchik|Yura Sokolov|Alexey Romanovsky|Jaume Marhuenda Beltran|Piotr Dulikowski|Tushar Das|Bogdan-Ciprian Rusu|Krishna Vadali|Jens-W. Schicke-Uffmann|Lauro Ramos Venancio|Dmitry Kropachev|Oliver Boyle" --pretty=format:"%H" | xargs -I {} git diff-tree --no-commit-id --name-only -r {} | sort | uniq)
```

**Comment by nathj07** [comment]
I'm sorry, but I believe I have done everything that was requested. 

Please proceed with my consent for this copyright reassignment.

**Comment by michaelsembwever** [comment]
Created
- https://github.com/gocql/gocql/pull/1772
- https://incubator.apache.org/ip-clearance/cassandra-gocql-driver.html

**Comment by Zariel** [comment]
I want to thank everyone that has agreed and signed over their contributions to the Apache Foundation and all those that have contributed to gocql over the years and finally to Mick for driving this donation process.

**Comment by petehatduck** [comment]
I have no idea how my name became attached to this project

Pete Hopkins
Sent from my iPhone

On 23 Jun 2024, at 18:03, mck ***@***.***> wrote:

﻿

Thank you everyone for taking the time to update this issue, or email us back.

We are ready to move forward with the donation.

We currently have 71 authors that we haven't been able to reach, whom in total touch 78 commits.
If you know of any of these people and have contact details for them, please help us and ping them to this issue.

If we do not hear from them we will either a) assume we have taken all reasonable actions (due diligence) to contact them and make the copyright re-assignment in good faith and in spirit with the majority that have agreed, or b) dual license and copyright work they have contributed (that still exists in master and v2.dev).

They are the following:

Christoph Hack @tux21b<https://github.com/tux21b>
Matt Robenolt @mattrobenolt<https://github.com/mattrobenolt>
Niklas Korz  @niklaskorz<https://github.com/niklaskorz>
Nimi Wariboko Jr ??
Ghais Issa @ghais<https://github.com/ghais>
Sasha Klizhentas ??
Konstantin Cherkasov @coxx<https://github.com/coxx> @kofatol<https://github.com/kofatol>
Ben Hood @0x6e6562<https://github.com/0x6e6562>
Pete Hopkins @petehatduck<https://github.com/petehatduck> @petehopkins<https://github.com/petehopkins>
Maxim Bublis @satori<https://github.com/satori>
Alex Zorin @alexzorin<https://github.com/alexzorin>
Kasper Middelboe Petersen @fantyz<https://github.com/fantyz>
Harpreet Sawhney @harpreet-sawhney<https://github.com/harpreet-sawhney>
Stanislavs Koikovs @skoikovs<https://github.com/skoikovs>
Dan Forest @dbxfb<https://github.com/dbxfb>
Stefan Radomski @sradomski<https://github.com/sradomski>
Josh Wright @JshWright<https://github.com/JshWright>
Jacob Rhoden @Jacobr23<https://github.com/Jacobr23>
Ben Frye @benfrye<https://github.com/benfrye>
Muir Manders @muirdm<https://github.com/muirdm>
Julien Da Silva @juliendsv<https://github.com/juliendsv>
Nick Dhupia ??
Matthias Kadenbach ??
Dean Elbaz @deane<https://github.com/deane>
Mike Berman @mikebthun<https://github.com/mikebthun>
Zach Marcantel @zmarcantel<https://github.com/zmarcantel>
James Maloney @ james-maloney @Jpmaloiv<https://github.com/Jpmaloiv> @Jimmy3850<https://github.com/Jimmy3850>
Miles Delahunty @mdelah<https://github.com/mdelah>
Zach Badgett @zachbadgett<https://github.com/zachbadgett>
Maciek Sakrejda @msakrejda<https://github.com/msakrejda>
Jeff Mitchell @jefferai<https://github.com/jefferai>
Matt Heath @mattheath<https://github.com/mattheath>
Jamie Cuthill @jamiecuthill<https://github.com/jamiecuthill>
Daniel Cannon @dancannon<https://github.com/dancannon>
Johnny Bergström @balboah<https://github.com/balboah>
Ference Fu @fym201<https://github.com/fym201>
LOVOO @lovoo<https://github.com/lovoo>
Viktor Tönköl @tonkolviktor<https://github.com/tonkolviktor>
Ian Lozinski ??
Michael Highstead @Highstead<https://github.com/Highstead>
Mark M @mark-i-m<https://github.com/mark-i-m>
Bartosz Burclaf ??
Marcus King @marcusking01<https://github.com/marcusking01> @king-mork<https://github.com/king-mork> @marcus-king<https://github.com/marcus-king> @marcusKng01<https://github.com/marcusKng01>
Andrew de Andrade @andrewdeandrade<https://github.com/andrewdeandrade>
Robert Nix @robert-nix<https://github.com/robert-nix> @rpural<https://github.com/rpural> @robertcnix<https://github.com/robertcnix> @rnix<https://github.com/rnix> @robertnix<https://github.com/robertnix>
Nathan Davies @nathj07<https://github.com/nathj07>
Bo Blanton @uacfboblanton @bobbdelsol
Derrick Wippler @thrawn01
Leigh McCulloch @leighmcculloch
Ron Kuris @rkuris
Raphael Gavache @raphaelgavache
Yasser Abdolmaleki ??
Krishnanand Thommandra @kthommandra
Blake Atkinson @robusto
Dharmendra Parsaila ??
Javier Zunzunegui @JavierZunzunegui
Chang Liu @changliuau
Jacob Greenleaf @jacobgreenleaf
Pavel Buchinchik @Bychin
Yura Sokolov @funny-falcon-at-joomcode
Alexey Romanovsky @alexus1024
Jaume Marhuenda Beltran @beltran
Piotr Dulikowski @piodul
Árni Dagur @ArniDagur
Tushar Das @tushardas
Bogdan-Ciprian Rusu @bcrusu
Krishna Vadali @saikrishnavadali05 @kkvadali @vadalikrishna @wq4885 @SaiKrishna0778
Jens-W. Schicke-Uffmann @Drahflow
Lauro Ramos Venancio @laurovenancio
Dmitry Kropachev @ dkropachev
Oliver Boyle @olib963

**Comment by marcusKng01** [comment]
What is this?

**Comment by mattrobenolt** [comment]
I mean, I'm not sure I like the fact that my lack of consent translates implicitly into consent.

I have not filled out the CLA since I'm not even sure if any of my code exists in HEAD anymore from contributions I made to this project literally 11 years ago and haven't spent the effort to figure that out.

**Comment by michaelsembwever** [comment]
> I have not filled out the CLA since I'm not even sure if any of my code exists in HEAD anymore from contributions I made to this project literally 11 years ago and haven't spent the effort to figure that out.

@mattrobenolt 
your work in the project looks to be these two commits:
- https://github.com/gocql/gocql/commit/a1bebffbf3f0c523562c65a67f78e8c017b82dd8
- https://github.com/gocql/gocql/commit/e4af0ccb49ec2b8a9f87301a62a8602b45a2a126

Are you happy for this to work to be part of gocql driver being donated to the Apache Cassandra project ?

**Comment by msakrejda** [comment]
+1; no objection to my commits being included.

**Comment by michaelsembwever** [comment]
> What is this?

Apologies @marcusKng01 , we're trying to reach the `Marcus King` that is listed in this project's authors file.  Please ignore, I've scrapped your github name from the possibilities.

**Comment by skoikovs** [comment]
+1 from me as well. Pretty sure there is no code authored by me left in
HEAD.

**Comment by relistan** [comment]
> I mean, I'm not sure I like the fact that my lack of consent translates implicitly into consent.
> 
> I have not filled out the CLA since I'm not even sure if any of my code exists in HEAD anymore from contributions I made to this project literally 11 years ago and haven't spent the effort to figure that out.

That's not what is happening, they are making a good faith effort (as you can well see) to contact everyone. They proposed two remedies above include dual licensing for code that is not signed over.

If you read the above explanations, it also doesn't matter if your code is on HEAD or not, they are trying to contribute the project including its history. Since it seems you don't care, you could just accede to it and let the project move forward. It actually took as much effort to write what you did as it would to sign it over.

**Comment by michaelsembwever** [comment]
> I'm happy to announce that Kiwi.com signed the Corporate CLA and the company agrees for all contributions that are owned by Kiwi.com in the gocql project's code repository and its forks available at https://github.com/gocql/gocql, https://github.com/kiwicom/gocql and https://github.com/scylladb/gocql to be donated to the Apache Software Foundation using the Corporate CLA. 

I can confirm that it has been received and filed by the ASF.

**Comment by ghais** [comment]
Signed and I have received confirmation from ASF

**Comment by ArniDagur** [comment]
I haven't signed the CLA, but I'm happy to donate my past contributions to the ASF. I saw this thread on day one, but I have been procrastinating signing the CLA given the headache involved.

**Comment by tushardas** [comment]
I'm happy to donate my contributions to ASF. Haven't signed the CLA though.

**Comment by relistan** [comment]
This took me about two minutes. No headache.

**Comment by michaelsembwever** [comment]
The donation has happen.  Once again I'd like to express thanks to everyone who helped make this project and everyone that popped in again to agree to the donation of the project.  It's exciting to see this project and all your work find new momentum.

If you're late to the party, still please do feel free to add your agreement to this ticket.  I will pay attention and keep the NOTICE file updated accordingly.

For those interested further migration steps are happening in https://issues.apache.org/jira/browse/CASSANDRA-19723
and discussions are sometimes happening in https://the-asf.slack.com/archives/C05LPRVNZV1 

Otherwise GH issues and pull requests here are still used (as they were).

**Comment by Highstead** [comment]
LGTM 👍 Sorry i was out for a bit.  Feel free to take whatever i contributed to here in the past.

**Comment by olib963** [comment]
This was lost in a sea of GitHub notifications, I didn't contribute much, I'm happy to have those contributions used.

**Comment by michaelsembwever** [comment]
Thanks @Highstead and @olib963 , is getting noted in https://github.com/apache/cassandra-gocql-driver/pull/1804

**Comment by bx2** [comment]
+1 from me - Bartosz Burclaf

**Comment by Drahflow** [comment]
@michaelsembwever I have received copyright-assignment back from the client who paid for my (minor) contributions, and am happy to donate said copyright to the ASF.

**Comment by marcusking01** [comment]
+1

**Comment by mattheath** [comment]
@michaelsembwever I'm happy to assign any contributions I've made to this to the ASF. Sorry for the delay!

**Comment by bcrusu** [comment]
My contribution was minimal, but I'm happy to donate it. Apologies for the late reply!

**Comment by michaelsembwever** [comment]
Hi @bcrusu ~can you let me know who in the https://github.com/apache/cassandra-gocql-driver/blob/34fdeebefcbf183ed7f916f931aa0586fdaa1b40/AUTHORS file you are~

Found it: https://github.com/apache/cassandra-gocql-driver/commit/769848eae4625444c6abdabc4a67eacb117c9200#diff-ab6af77435f58cc0c9d4c31dfe05656e45187cc7c7fc02aada401a7642125463R125

**Comment by purohit** [comment]
+1
